# Generated by Django 2.1.7 on 2019-07-23 02:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0005_auto_20190723_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='adicionado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Adicionado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autor',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Eliminado'),
        ),
    ]
