# Generated by Django 2.2.4 on 2019-10-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0006_auto_20190723_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Modificado'),
        ),
    ]
